test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

oci:
  service: S3
  access_key_id: <%= ENV['OCI_KEY'] %>
  secret_access_key: <%= ENV['OCI_SECRET'] %>
  bucket: <%= ENV['BUCKET'] %>
  region: <%= ENV['OCI_REGION'] %>
  # endpoint: https://<%= ENV['OCI_NAMESPACE'] %>.compat.objectstorage.<%= ENV['OCI_REGION'] %>.oraclecloud.com
  endpoint: <%= ENV['OCI_ENDPOINT'] %>
  force_path_style: true

# mirror:
#   service: Mirror
#   primary: local
#   mirrors: [ amazon, google, microsoft ]
