test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

oci:
  service: S3
  access_key_id: <%= Rails.application.credentials[:oci][:key] %>
  secret_access_key: <%= Rails.application.credentials[:oci][:secret] %>
  bucket: <%= Rails.application.credentials[:oci][:bucket] %>
  region: <%= Rails.application.credentials[:oci][:region] %>
  endpoint: <%= Rails.application.credentials[:oci][:endpoint] %>
  force_path_style: true

# mirror:
#   service: Mirror
#   primary: local
#   mirrors: [ amazon, google, microsoft ]
